#!/bin/sh

# Usage
# tools/visit -nosplash -o hex.xdmf2

AfterO=0
for i
do case $AfterO in
     0) case $i in
	    -o) AfterO=1 ;;
	    *) AfterO=0 ;;
	esac
	;;
     1) case $i in
	    *.xdmf2) i=$i,Xdmf
		     ;;
	esac

   esac
   shift
   set -- "$@" "$i"
done

exec visit "$@"
